defaults:
  - _self_
  - preset: null

# dataset should have columns "messages" and "resolved"
dataset:
  name: "SWE-bench/SWE-smith-trajectories"
  split: "xml"
model: "Qwen/Qwen2.5-Coder-7B-Instruct"