defaults:
  - _self_
  - preset: null

# dataset should have columns `messages` and `resolved`
dataset:
  path: "SWE-bench/SWE-smith-trajectories"
  split: "xml"

model:
  name: "Qwen/Qwen2.5-Coder-7B-Instruct"
  
trainer:
  output_dir: "trainer_outputs"
  bf16: true
  gradient_checkpointing: true