# @package _global_

model:
  pretrained_model_name_or_path: "Qwen/Qwen2.5-Coder-7B-Instruct"
  attn_implementation: sdpa
  dtype: bfloat16
tokenizer:
  model_max_length: 32768

dataset:
  path: data
  data_files: my-SWE-smith-trajectories.parquet
  split: train

data_collator:
  pad_to_multiple_of: 8

trainer:
  observation_loss_weight: 0.1
  chunked_cross_entropy: true
  chunked_cross_entropy_kwargs:
    chunk_size: 1024
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 32
  num_train_epochs: 1
  learning_rate: 5e-5
  lr_scheduler_type: cosine
  warmup_steps: 5
  weight_decay: 0.01
  optim: paged_adamw_8bit
  seed: 42
  bf16: true
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false
  save_strategy: steps
  save_steps: 20
  save_total_limit: 2
  logging_steps: 1
  report_to: wandb
  run_name: train
  