resources:
  infra: runpod
  accelerators: L40S:1
  disk_size: 256

workdir: .

envs:
  WANDB_PROJECT: echo-sft
  WANDB_LOG_MODEL: false

secrets:
  WANDB_API_KEY: null

setup: |
  uv sync

run: |
  uv run main.py preset=train