resources:
  infra: runpod
  accelerators: A100-80GB:1
  disk_size: 256

workdir: .

envs:
  WANDB_PROJECT: echo-sft
  WANDB_LOG_MODEL: false
  PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True

secrets:
  WANDB_API_KEY: null

setup: |
  uv sync
  uv pip install wandb bitsandbytes

run: |
  uv run main.py preset=train