resources:
  infra: runpod
  accelerators: A100-80GB:1
  disk_size: 256

workdir: .

envs:
  WANDB_PROJECT: swe-smith-ocd
  WANDB_LOG_MODEL: false
  PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True

secrets:
  WANDB_API_KEY: null
  HF_TOKEN: null

setup: |
  uv sync
  uv run jupyter execute dataset.ipynb

run: |
  uv run train.py env=remote